name: CI 
on: [push, pull_request]
jobs:
  black:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: isort/Black
        run: |
          pip install isort black
          isort --check $(git ls-files '*.py')
          black --check $(git ls-files '*.py')
