name: CI 
on: [push, pull_request]
env:
  SPELL_CHECK: 'false'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - python-version: "2.7"
            os: ubuntu-latest
          - python-version: "3.6"
            os: ubuntu-latest
        include:
          - python-version: "3.6"
            os: ubuntu-20.04
            lib: libenchant1c2a
          - python-version: "2.7"
            os: ubuntu-20.04
            lib: libenchant1c2a
            pylint-rcfile: "--rcfile=.pylintrc-27"
          - python-version: "2.7"
            os: macos-latest
            pylint-rcfile: "--rcfile=.pylintrc-27"
          - python-version: "2.7"
            os: windows-latest
            pylint-rcfile: "--rcfile=.pylintrc-27"
    runs-on: ${{matrix.os}} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install enchant (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get -y install --no-install-recommends ${{matrix.lib}} libenchant-2-dev aspell-en libaspell-dev
        env:
          SPELL_CHECK: 'true'
      - name: Install enchant (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install enchant
        env:
          SPELL_CHECK: 'true'
      - name: Install BittyTax
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Pylint (with spelling check)
        if: ${{ env.SPELL_CHECK == 'true' }}
        run: |
          pip install pylint pyenchant
          pylint ${{matrix.pylint-rcfile}} --spelling-dict=en_GB $(git ls-files '*.py')
      - name: Pylint
        if: ${{ env.SPELL_CHECK == 'false' }}
        run: |
          pip install pylint
          pylint ${{matrix.pylint-rcfile}} $(git ls-files '*.py')
      - name: Flake8
        run: |
          pip install flake8
          flake8 .
      - name: isort/Black
        if: ${{ matrix.python-version > 3.6 }}
        run: |
          pip install isort black
          isort --check $(git ls-files '*.py')
          black --check $(git ls-files '*.py')
