name: CI 
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Install BittyTax
        run: pip install -e .
      - name: Lint 2.7
        run: pylint --rcfile=.pylintrc-27 $(git ls-files '*.py')
        if: ${{matrix.python-version}} == "2.7"
      - name: Lint 3.x
        run: pylint $(git ls-files '*.py')
        if: ${{matrix.python-version}} != "2.7"
