name: CI 
on: [push, pull_request]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install BittyTax
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Install libenchant packages
        run: |
          sudo apt-get -y install --no-install-recommends libenchant-2-dev aspell-en libaspell-dev
      - name: Pylint (with spelling check)
        run: |
          pip install pylint pyenchant
          pylint --spelling-dict=en_GB $(git ls-files '*.py')
